[package]
name = "calc_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.38"
syn = { version = "2.0.96", features = ["full"] }
calc = { path = "../calc" }
